on:
  push:
    branches-ignore:
      - '**.tmp'

name: test

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.47.0

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: apg-get update
        run: sudo apt-get -o Acquire::Retries=3 update
      - name: Install libsystemd-dev
        run: sudo apt-get -o Acquire::Retries=3 install libsystemd-dev

      - name: Check with only journal
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
